CONFIG_GPIO=y
CONFIG_PWM=y
# CONFIG_DMA=y

CONFIG_ZERO_LATENCY_IRQS=y

# CONFIG_MAIN_STACK_SIZE=4096
# CONFIG_ISR_STACK_SIZE=4096

# CONFIG_PRINTK=n
CONFIG_LOG=n

# just for filter coef calc
CONFIG_FPU=y

# REQUIRED FOR Q15 control + filtering
CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_DSP_FILTERING=y
CONFIG_CMSIS_DSP_CONTROLLER=y


# SRAM ISR
CONFIG_SRAM_VECTOR_TABLE=y
# CONFIG_SRAM_SW_ISR_TABLE=y
